### ISSUE TITLE
where is the inference coda?

### ISSUE THREAD

**Issue by wangchangquan** [Guiliang/ICRL-benchmarks-public#2]
All you introduce is trainning code , but  where is the inference code ? especial for the Run Realistic Benchmark.

**Comment by Guiliang** [comment]
Hi, I am wondering what you mean by inference code. The idea of VICRL is to approximate the constraints with a neural function. This is the cost function in our code. Each time it will let you know whether the state-action pair is allowed. If you indicate the testing code, we have the evaluation during training, and you can use the same function for testing.
